### ISSUE TITLE
How can I read or receive messages

### ISSUE THREAD

**Issue by InfoTI89** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#10]
@gabrieldwight 
First of all, thanks for the library, it is of great support for any research project.

I have a problem that I can't solve.
How can I read or receive the messages that a contact writes to me, I have already tried everything, I have configured the WebHooks from Meta, through the Glitch I can read the messages, but not through the methods of this project.
Could you give me a hand?

**Comment by gabrieldwight** [comment]
@InfoTI89 You can use [Conveyor Extension](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1448185.ConveyorbyKeyoti) to test your ASP.NET webhook endpoint locally as long as you have added the locally generated endpoint to Meta webhook subscription for testing then you can change to your production endpoint. For the sample project context, I used the conveyor extension for reading and receiving WhatsApp messages sent by the contact. **One thing to note: You need to verify the endpoint generated by Conveyor to Meta if the generated verification token matches**

**Comment by InfoTI89** [comment]
thanks for the info, i will try it

**Comment by gabrieldwight** [comment]
@InfoTI89 Let me know if the conveyor extension solves your issue with receiving messages in the project context.

**Comment by InfoTI89** [comment]
I'm trying, is there a test version of the conveyor? Currently it is asking me to make a payment to enable the settings.

![image](https://user-images.githubusercontent.com/110925372/184238364-05ebb18a-c9b9-4858-a8b8-610637dd6572.png)

**Comment by gabrieldwight** [comment]
For the custom settings, you will need the pro version. If you click **access over internet** it will generate the internet URL that can be used for testing when debugging the project.

**Comment by InfoTI89** [comment]
Can you tell me why it tells me to start a project? Apologies in advance for the insistence.

![image](https://user-images.githubusercontent.com/110925372/184247240-e060efcb-9912-4b2b-9358-dea76c5d0fcf.png)

**Comment by gabrieldwight** [comment]
You run your project in debug mode. Once the project is running, you click access over the internet, it will successfully generate a temporary internet URL for testing.
