### ISSUE TITLE
working in local not working in server

### ISSUE THREAD

**Issue by ki-erp** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#100]
**Describe the bug**
Unhandled Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 157.240.16.16:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at ConsoleApp1.Program.Main(String[] args)

**Comment by gabrieldwight** [comment]
Check your server if it is reachable from meta end when setting up the webhook and also check your server firewall configuration if it is getting a connection from meta.

**Comment by ki-erp** [comment]
Ok, thanks for reply,

I checked it was an Firewall issue.

Can u provide any example for asp.net MVC app. With webhook integration, i
want implement WhatsApp page for replying to sender did we have any built
in plugin for that, please help if you know the same, thanks in advanced.

**Comment by gabrieldwight** [comment]
You can have a look at this [example](https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net/blob/master/Samples/WhatsAppBusinessCloudAPI.Web/Controllers/WhatsAppNotificationController.cs) The notification controller act as a webhook.

**Comment by ki-erp** [comment]
I turn off firewall but same error, how can I check reachable from meta or not?

**Comment by gabrieldwight** [comment]
ping your server with another device to see if it is reachable

**Comment by ki-erp** [comment]
Thank you for your reply, I got the issue AWS is Blocked outbound TCP port 80, 8080, 443 that’s why it’s not working, let me coordinate with them and get back to you with better result, thanks again.
