### ISSUE TITLE
(#100) Invalid parameter when sending InteractiveMessageDateTime

### ISSUE THREAD

**Issue by sotskopa** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#105]
When sending InteractiveTemplateMessageRequest, I get Invalid parameter, Code 100 from the Graph API. I believe this is because InteractiveMessageDateTime has a bunch of default parameters that are not ignored when serializing into the POST payload, e.g. DayOfWeek, Year, Month, and so on. [The Cloud API expects only fallback_value in a date_time](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#date-time-object), so adding NullValueHandling or removing these properties is preferred.

**Comment by gabrieldwight** [comment]
I will push an update with the fix for NullValueHandling of InteractiveMessageDateTime.
