### ISSUE TITLE
Allow media headers for interactive reply button messages

### ISSUE THREAD

**Issue by cyrodiil** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#114]
Interactive reply button messages now also allow media headers:
https://developers.facebook.com/docs/whatsapp/cloud-api/messages/interactive-reply-buttons-messages

Could you please implement the media headers for those messages?
Thank you!

**Comment by gabrieldwight** [comment]
Hi, I will review the documentation for the media headers for reply button messages.
