### ISSUE TITLE
Create class UserInitiatedMessageReadStatus

### ISSUE THREAD

**Issue by IanosJunior** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#115]
Create this class to complete the Webhook example
![image](https://github.com/user-attachments/assets/a41870c5-517c-4f03-9277-8c015c454449)

**Comment by gabrieldwight** [comment]
The user-initiated class was for old graph API versions. You can use the MessageStatusUpdateNotification class to handle message status for sent, read and delivered since it's for latest graph API version
