### ISSUE TITLE
SendWhatsAppTextMessage does not send message in test project

### ISSUE THREAD

**Issue by han66601** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#19]
### Discussed in https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **Catronis** October 13, 2022</sup>
Hello, I downloaded the project a week ago and did some testing, a simple message sent correctly. I downloaded the most current version again today but it doesn't send a message, template sends normally. However, it notifies that the message has been sent, but does not reach whatsapp.</div>

**Comment by han66601** [comment]
> ### Discussed in #17
> Originally posted by **Catronis** October 13, 2022 Hello, I downloaded the project a week ago and did some testing, a simple message sent correctly. I downloaded the most current version again today but it doesn't send a message, template sends normally. However, it notifies that the message has been sent, but does not reach whatsapp.

111111

**Comment by gabrieldwight** [comment]
@han66601  Which error code are you getting when sending a message?
