### ISSUE TITLE
Message sent with marked success alert, but I don't get a message on whatsapp?

### ISSUE THREAD

**Issue by mbsysde99** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#22]
Message sent with marked success alert, but I don't get a message on whatsapp? What is the solution to this problem? 

Thanks and Regards,
Yudha

![image](https://user-images.githubusercontent.com/38758714/200555731-ba70d955-48bf-4038-9ba7-1ecca7e42e96.png)

**Comment by gabrieldwight** [comment]
@mbsysde99 If you are using a test phone number from Meta. Send the hello world template message from the test console and reply message with any text. After that, you will be able to receive a WhatsApp message from the test phone number.

**Comment by mbsysde99** [comment]
> @mbsysde99 If you are using a test phone number from Meta. Send the hello world template message from the test console and reply message with any text. After that, you will be able to receive a WhatsApp message from the test phone number.

Thanks Brother, Now its worked!
