### ISSUE TITLE
how to add multiple number in "To" named property?

### ISSUE THREAD

**Issue by kingsanu** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#29]
may i know brother that how can i add multiple number into "To"  named property ?
![image](https://user-images.githubusercontent.com/47456495/209660995-341fe31a-b4b8-456c-965a-47eab9a8000f.png)

**Comment by gabrieldwight** [comment]
At the moment cloud api does not support multiple phone numbers assigned to "To" property. The other workaround is to create an array of textMessageRequest and send the message in the loop. Be aware of the rate-limiting 500 messages per second.
