### ISSUE TITLE
[Information]Whatsapp error (#100) Invalid parameter on phone number

### ISSUE THREAD

**Issue by Tekkharibo** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#31]
Hi,

Since the 2023 January 23 I can't send any message with the lib because I have the error `(#100) Invalid parameter` 

I have found why I have this error.

The international phone number can write with two typing (French number for example) 
- `+33 6 xx xx xx xx`
- `0033 6 xx xx xx xx`

But the Whatsapp API, since this date don't allow the format `0033 6 xx xx xx xx`

I think that was interested to add this information on the `README.md` 

Regards

**Comment by gabrieldwight** [comment]
Hi, for the French number does it work to send a message using this format `33 6 xx xx xx xx`? 

Is it returning an invalid phone number under the error data property in the details property?

Regards

**Comment by Tekkharibo** [comment]
Yes the format `33 6 xx xx xx xx` work fine ;) 

With the `0033 6 xx xx xx xx` format I just have `(#100) Invalid parameter` and `Parameter Invalid` on `whatsAppErrorResponse.Error.ErrorData/Details`

![image](https://user-images.githubusercontent.com/4319715/218071179-a327c082-9a0f-4028-bcd2-2425e5a5fc88.png)

Regards

**Comment by gabrieldwight** [comment]
That's fine. I will add to the readme this information where it applies to any number format with the prefix `00` before the **country code** will through the invalid parameter error.
