### ISSUE TITLE
Why is the Footer-Property is missing?

### ISSUE THREAD

**Issue by Chief4Master** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#36]
Hello!

I would like to send a custom footer with various message types. 
But none of these (except the InteractiveListMessageRequest) have a footer property (e.g. InteractiveReplyButtonMessageRequest). How should I do this (I only saw the class WhatsappBusiness.CloudApi.Messages.Requests.Footer but this is implemented only on the InteractiveListMessageRequest) or do you plan to implement this?

Best regards

**Comment by gabrieldwight** [comment]
Hi, I planned this week to implement the footer property for InteractiveReplyButtonMessageRequest and check if other message types apart from the interactive messages support the same footer property.
