### ISSUE TITLE
New Authentication Messages not supported

### ISSUE THREAD

**Issue by borrmann** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#44]
The WhatsApp Cloud API for sending authentication messages has changed and I think authentication messages are not supported with current version anymore. Here is the link to the docs how a authentication message looks like now:

[WhatsApp Cloud Docu](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-message-templates/auth-otp-template-messages)

```
{
  "messaging_product": "whatsapp",
  "recipient_type": "individual",
  "to": "<CUSTOMER_PHONE_NUMBER>",
  "type": "template",
  "template": {
    "name": "<TEMPLATE_NAME>",
    "language": {
      "code": "<TEMPLATE_LANGUAGE_CODE>"
    },
    "components": [
      {
        "type": "body",
        "parameters": [
          {
            "type": "text",
            "text": "<ONE-TIME PASSWORD>"
          }
        ]
      },
      {
        "type": "button",
        "sub_type": "url",
        "index": "0",
        "parameters": [
          {
            "type": "text",
            "text": "<ONE-TIME PASSWORD>"
          }
        ]
      }
    ]
  }
}
```

The TextMessageComponent currently only takes TextMessageParameters, but to send a one-time password other options should be addable to the List of TextMessageComponents

**Comment by gabrieldwight** [comment]
I will add implementation for the authentication message template with the new change.

**Comment by gabrieldwight** [comment]
Added the implementation of the authentication message template

![image](https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net/assets/28096255/3b72bfc6-a610-4c12-9499-5fe3d5fe3b88)
