### ISSUE TITLE
Unexpected key "add_security_recommendation" When sending authentication message 

### ISSUE THREAD

**Issue by OmarAbdelrazek** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#50]
**Describe the bug**
this exception is appeared in the latest version (1.0.21).

**To Reproduce**
1. Create authentication message template.
2. Try [Sending Authentication Message](https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net#sending-authentication-message) example and the error will be shown.

**Additional context**
version (1.0.20) works fine.

**Comment by gabrieldwight** [comment]
Hi, thanks for the issue, I have pushed the fix on the next update.

**Comment by OmarAbdelrazek** [comment]
Thank you for your prompt assistance in resolving the issue. Much appreciated!
