### ISSUE TITLE
Question: functionality to get the list of business account user's phone numbers 

### ISSUE THREAD

**Issue by madhugilla** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#53]
Hi, 

Scenario: we want to get the list of user phone numbers who used a WhatsApp business account over a period of time (ex: last 2 months)

questions
1) is there an method in the sdk that supports this feature?
2) does whatsapp even expose an api to support this ?

THanks -Nen

**Comment by gabrieldwight** [comment]
Hi, currently the only method available from the API is to get the list of phone numbers registered with the business account. [Retrieve phone numbers](https://developers.facebook.com/docs/whatsapp/business-management-api/manage-phone-numbers/).

The other way to get the phone numbers based on a period of time can use the [Analytics API](https://developers.facebook.com/docs/whatsapp/business-management-api/analytics) but it can either be based on analytics or conversion analytics
