### ISSUE TITLE
Send bulk messages

### ISSUE THREAD

**Issue by jayadevc** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#62]
I was trying to send bulk messages by adding comma separated phone numbers in RecipientPhoneNumber, but getting invalid parameter error. 

TextMessageRequest textMessageRequest = new();
textMessageRequest.To = "1122334455,1122334456";

Is there an alternative to send bulk messages in single api?

**Comment by gabrieldwight** [comment]
Cloud api currently does not support bulk messages in single API call. You will have to do your own implementation to manage sending messages in bulk.
