### ISSUE TITLE
Error when download media from url

### ISSUE THREAD

**Issue by pablosanchezuy** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#70]
var results = _whatsAppBusinessClient.GetMediaUrl(id);
var imageBytes = _whatsAppBusinessClient.DownloadMedia(results.Url); //I have an error on this line

Exception captured
System.ArgumentException: 'The value cannot be null or empty. Arg_ParamName_Name'
![exception](https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net/assets/26327874/69b8ded9-606f-4ec8-88d6-9ca5086b9903)

**Comment by gabrieldwight** [comment]
If it is an old media id, then it was either deleted earlier by WhatsApp or it is passed 30 days on persistence from their end. Remember the media URL from the media id expires after 5 minutes which you will have to retrieve again when expired.

**Comment by gabrieldwight** [comment]
Hi, I will investigate on the error for the media url to see where the
issue is coming from. By any chance are you trying to get url from a video
media

**Comment by gabrieldwight** [comment]
@pablosanchezuy I'm not from Brazil.
On my side, I'm able to get the media URL after uploading the media as you can see below:
![image](https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net/assets/28096255/0d36f2e0-0249-4bf8-b023-f0fbc6e43265)

Please make sure you check the results returned from getmediaurl function returns the file size greater than zero and also check on the content type returned from the function.

using the same URL from the result to download the media without any issue as you can see the mediaBytes length is not zero.
![image](https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net/assets/28096255/dc91efc4-5cfa-44aa-9ded-c57018db6e42)

**Comment by pablosanchezuy** [comment]
Hello Gabriel, run ok in this line:
GetMediaUrlAsync

[image: image.png]

But when execute this method: DownloadMediaAsync
I obtain an exception
it's very strange


[image: image.png]

Anyway thank you very much
Greetings


Pablo Sánchez

**Comment by portisk8** [comment]
@pablosanchezuy  The same error happened to me. And it was because I was not passing these parameters in WhatsAppBusinessCloudApiConfig:
* AppName
* Version
Are you passing these parameters in WhatsAppBusinessCloudApiConfig?
![image](https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net/assets/9359059/c0eb8c47-7a34-4f19-8ffc-82287af06560)

**Comment by gabrieldwight** [comment]
@pablosanchezuy  From version 18 and above of graph API will require to pass the AppName and Version if you want the download media function to work

**Comment by pablosanchezuy** [comment]
Hi Gabriel, how are you?
I was not passing on those attributes to her, that is surely the mistake.
I'm going to correct it
Thanks you
Regards

Pablo Sánchez

**Comment by gabrieldwight** [comment]
Hi Pablo, I'm doing fine. You can let me know if the above attributes work on your side.
