### ISSUE TITLE
"Reply to Message" feature is not marking messages as replies in certain scenarios

### ISSUE THREAD

**Issue by AmonApolonio** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#71]
**When replying to a message, the message is sent but not marked as replying (with some exceptions)**
The feature "reply to message" doesn't work when the system is replying to a message the user sent, but is working when:
1. Replying to a message the user sent replying to other message
2. Replying to a message the system sent

![issue_whatsapp_reply](https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net/assets/67078597/41cec1d2-3711-4346-a380-b1d678e0dfb3)

**To Reproduce**
```      
        var textMessageReplyRequest = new TextMessageReplyRequest
        {
            Context = new TextMessageContext { MessageId = request.QuotedMessageId },
            To = request.Number,
            Text = new WhatsAppText
            {
                Body = request.Text,
                PreviewUrl = false
            }
        };

        var results = await _whatsAppBusinessClient.SendTextMessageAsync(textMessageReplyRequest, null, cancellationToken);
```

**Comment by gabrieldwight** [comment]
the user sending the message to the system it will be identified as a user-initiated conversation on cloud api. To reply to the user-initiated conversation you will need to handle the reply request on the webhook level.

**Comment by AmonApolonio** [comment]
Oh, I managed to make the **_whatsAppBusinessClient.SendTextMessageAsync()** function work for replying to user messages, by updating the Cloud API version from v18.0 to v19.0. However, only this reply request is functional; the others, like audio/document/contact reply requests, still do not work even after the Cloud API version update. I'm not quite sure why.

**Comment by gabrieldwight** [comment]
I will check on the changelogs for graph API v19.0 to see what has changed for different message reply requests.
