### ISSUE TITLE
FIX: Error MarkMessageAsRead wrong API Method

### ISSUE THREAD

**Issue by Tekkharibo** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#8]
Hi,

Thank you so much for this lib

I have an error with the function MarkMessageAsRead because that send request on `PUT` method but the Whatsapp API need a `POST` method

### Error message:
```Unsupported put request. Object with ID 'xxx' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api```
[Whatsapp documentation MarkMessageAsRead](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/mark-message-as-read)

### Version
v1.0.2

### Solve Issue

Need to update code on file `WhatsAppBusinessClient.cs` at line `205` and `211` update `WhatsAppBusinessPutAsync` by `WhatsAppBusinessPostAsync`

PS: I have never do a pull request, I will be try tomorrow for this fix

**Comment by gabrieldwight** [comment]
@Tekkharibo Thanks for identifying the error message for MarkMessageAsRead. I will update it as soon as possible.

**Comment by gabrieldwight** [comment]
I have resolved the issue for MarkMessageAsRead.
