### ISSUE TITLE
Many numbers return "(#131026) Receiver is incapable of receiving this message"

### ISSUE THREAD

**Issue by laughinglion** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#80]
**Describe the bug**
Many numbers that we send messages to causes an exception with the message "(#131026) Receiver is incapable of receiving this message". Others are fine.
This behavior started about a week ago.

**Comment by gabrieldwight** [comment]
It can be due to many reasons but you can find more information about [undelivered messages](https://help.businesschat.io/en/articles/8368430-understanding-undelivered-messages)
