### ISSUE TITLE
WhatsAppBusinessCloudApiConfig Optional Parameter

### ISSUE THREAD

**Issue by julianodev** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#90]
Hello Gabriel,

Don't you think it would be interesting to pass WhatsAppBusinessCloudApiConfig as an optional parameter in all methods?

**Comment by gabrieldwight** [comment]
Hi Juliano,  I have added the optional parameter in all the sending messages methods since it is mostly used. I will see about the other methods that deals with business management api.

**Comment by julianodev** [comment]
Thanks for the answer. One method I need to pass was GetWhatsAppBusinessAccountPhoneNumberAsync as an example.

I tried to create the pull request to help. But I don't have permission.
