### ISSUE TITLE
how to send Location Template Message?

### ISSUE THREAD

**Issue by erikk-se** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#91]

**Comment by gabrieldwight** [comment]
Hi, i have not implemented the location template message functionality but alternatively, you can use the method **sendgenericmessageasync** but you will have to construct the object for location template message.

**Comment by erikk-se** [comment]
it work, thanks

**Comment by erikk-se** [comment]
> Hi, i have not implemented the location template message functionality but alternatively, you can use the method **sendgenericmessageasync** but you will have to construct the object for location template message.

it work, thanks
