### ISSUE TITLE
Document class is missing from WhatsappBusiness.CloudApi/Messages/Requests /InteractiveTemplateMessageRequest.cs

### ISSUE THREAD

**Issue by bashartaha** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#92]
Hi,

Im trying to send Interactive Template Message Request, with document but unfortunately its missing from the InteractiveMessageParameter class.

public class InteractiveMessageParameter
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("image", NullValueHandling = NullValueHandling.Ignore)]
        public InteractiveMessageImage Image { get; set; }

        [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
        public string Text { get; set; }

        [JsonProperty("currency", NullValueHandling = NullValueHandling.Ignore)]
        public InteractiveMessageCurrency Currency { get; set; }

        [JsonProperty("date_time", NullValueHandling = NullValueHandling.Ignore)]
        public InteractiveMessageDateTime DateTime { get; set; }

        [JsonProperty("payload", NullValueHandling = NullValueHandling.Ignore)]
        public string Payload { get; set; }

     //this section is missing
        [JsonProperty("document", NullValueHandling = NullValueHandling.Ignore)]
        public InteractiveMessageDocument Document { get; set; }
    } 
    
         //this section is missing
     public class InteractiveMessageDocument
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("link")]
        public string Link { get; set; }

        [JsonProperty("filename")]
        public string FileName { get; set; }
    }

**Comment by gabrieldwight** [comment]
Hi, I will add the missing class in the next update.

**Comment by bashartaha** [comment]
Thank you for the update, and I appreciate your help.

May I know when will be the next update?

**Comment by gabrieldwight** [comment]
Today
