### ISSUE TITLE
InteractiveMessageParameter Missing Video support

### ISSUE THREAD

**Issue by mokkymiah** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#97]
**Is your feature request related to a problem? Please describe.**
When using InteractiveMessageParameter, the video property is missing. 

**Describe the solution you'd like**
Please add 
```
   public InteractiveMessageParameter
   {
       [JsonProperty("video", NullValueHandling = NullValueHandling.Ignore)]
       public InteractiveMessageVideo Video { get; set; }

   }


   public class InteractiveMessageVideo
   {
       [JsonProperty("id")]
       public string Id { get; set; }

   }
```

**Describe alternatives you've considered**
We are currently using an override. However we are getting an error "Malformed token" but the message still goes through to whatsapp with the video attachment just fine.

```    public class ExtendedInteractiveMessageParameter : InteractiveMessageParameter
    {


        [JsonProperty("video", NullValueHandling = NullValueHandling.Ignore)]
        public InteractiveMessageVideo Video { get; set; }

    }

```

**Additional context**
Additional types available when creating template via meta:

![image](https://github.com/user-attachments/assets/e6425b5e-39de-4981-b533-f8fa9222f941)

**Comment by mokkymiah** [comment]
I have a branch ready but unable to push up to create a PR.

**Comment by gabrieldwight** [comment]
I will add the solution
