### ISSUE TITLE
How to handle received information on flow messages?

### ISSUE THREAD

**Issue by fercom** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#99]
Would you please add an example on how to handle the responses for a flow message in the WhatsApp Notification Controller?

I created my own flow on the whatsapp developers site but I am not sure in how to handle the responses that the users send when they fill the flow

**Comment by gabrieldwight** [comment]
Hi, I would add an example to handle a flow message received responses to the controller still looking for some time to review the flow message webhook documentation.

**Comment by fercom** [comment]
Ok, thanks!

Fer Galván
Intelligent Chatbots

El 13 ago 2024, a la(s) 6:27 a.m., Gabriel Odero ***@***.***> escribió:

﻿

Hi, I would add an example to handle a flow message received responses to the controller still looking for some time to review the flow message webhook documentation.
